- hosts: all
  become: true
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
  - name: Install a yum package in Ansible example
    yum:
      name: git
      state: present
  - name: install the latest version of Apache
    yum:
     name: httpd
     state: latest

  roles:
  - nginx